### ISSUE TITLE
App crashes when ad is closed (Unity 5)

### ISSUE THREAD

**Issue by Parziphal** [swisscodemonkeys/appbrain-sdk#5] opened 2016-03-02 17:49 UTC
I create a new Unity 5 game, place the SDK files in `Assets/Plugins/Android`, I create a button that will run `AppBrain.GetAds().ShowInterstitial(true);` when pressed, then I build and install the app, I press the button, and the "Would you like more free apps?" dialog appears. Everything seems fine.

But whether I press "Not now" right away, or close the interstitial after viewing it, the app crashes and closes too.

The logcat says this:

```
I/Unity   (23661): onDestroy
I/Process (23661): Sending signal. PID: 23661 SIG: 9
I/ActivityManager(17038): Process com.foo.bar (pid 23661) has died.
I/WindowState(17038): WIN DEATH: Window{4368b1e0 u0 com.foo.bar/com.unity3d.player.UnityPlayerActivity}
```

**Comment by mathijs81** [comment] 2017-06-09 08:10
We are looking into this problem and hope to provide a solution soon.
Does the user also see an error message when the app closes? The intended behavior of ShowInterstitial(true) is that the app closes after you're done with the interstitial (the true stands for that this is an exit interstitial).
Note that if you want to show an interstitial without your app closing (e.g. between levels) you should call ShowInterstitial(false).

**Comment by mathijs81** [comment] 2018-01-09 16:13
There have been multiple SDK releases since this problem. It should be fixed now, if not, please feel free to reopen.

**Closed by mathijs81** 2018-01-09 16:13 UTC
